//
//  NSPasteboard+Types.swift
//  Clipmighty
//
//  Extended pasteboard types for detecting sensitive content from password managers
//  and other standardized clipboard types.
//

import AppKit

// MARK: - Sensitive Clipboard Types
// Password managers (1Password, Bitwarden, etc.) use these pasteboard types
// to mark clipboard content as sensitive or auto-generated.

extension NSPasteboard.PasteboardType {
    /// Indicates the clipboard content is concealed (e.g., passwords)
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// Indicates the clipboard content was auto-generated (e.g., generated passwords)
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    // Standard Types Helpers
    static let jpeg = NSPasteboard.PasteboardType("public.jpeg")
    static let png = NSPasteboard.PasteboardType("public.png")
    static let tiff = NSPasteboard.PasteboardType("public.tiff")
}
